version: "3"
services:
  api:
    build: ./
    environment:
    - SERVICE=api
    - MYSQL_DATABASE=radio
    - MYSQL_USER=radiouser
    - MYSQL_PASSWORD=password
    - DB_SERVER=db
    ports:
    - "3000:80"
    image: "segleralex/stream-regular-check:latest"
    networks:
    - myswarmnet
  db:
    image: "mariadb:10.1"
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=radio
    - MYSQL_USER=radiouser
    - MYSQL_PASSWORD=password
    networks:
    - myswarmnet
    deploy:
      replicas: 1
    volumes:
    - ./latest.sql.gz:/docker-entrypoint-initdb.d/radio.sql.gz
networks:
  myswarmnet:
    driver: "overlay"
    driver_opts:
      encrypted: ""
